### PR TITLE
Database configurations

### PR DESCRIPTION
**Pull request by Simonlie0302**
@riccardobellini Is this a proficient solution for the mixed table configuration or do we need to integrate something like flyaway to manage version control?

### CODE REVIEW

**Comment by riccardobellini** [comment]
The mixed tables situation is happening due to a simple reason. When docker compose spins up the containers, it has to assign a name to them: normally, when using `docker run`, if not explicitly provided the container name is randomly generated. Compose, on the other hand, uses as default container name (if no options are specified) the following structure: `${basename_dir}-${services}-${progr}`. So, if you start your compose file as-is, the database container will be named `backend-db-1`. See [this documentation](https://docs.docker.com/compose/environment-variables/envvars/#compose_project_name) for reference.

The problem, in this situation, is that the basename of the directory is "backend" for both the first and second MVP, so even though the docker-compose file is not the same (is in different location), by default it's not able to use anything to distinguish the different "projects", so to speak. Hence you end up reusing the same container that was created for the first MVP.

To solve this problem, you need to either (just the simplest options):

1. Rename the backend folder (I do not recommend this).
2. Explicit a name for the Postgres container, which will be different from the one in the first MVP's docker compose file (as you did in this commit).
3. Specify a `name` variable in the compose config file (the cleanest one, in my opinion).

Note that there's no need to name the db, user and password differently, since the conflict is just due to using the same container. If you configure compose properly, another container will be created and you can keep the same credentials and names.

As a final note on Flyway: Flyway (as you might now guess from my explanation) has nothing to do with this issue and would not have solved this. It's a perfectly fine approach for progressively migrating and evolving the database schema alongside with the application code, but for this MVP is a bit overkill. We do not plan on evolving the application, so no incremental migration will have to be apply.
You can certainly try and experiment with it if you have time when all the features are complete, but it's not mandatory to use it.

Hope I was clear, let me know if further explanation is needed.

**Comment by Simonlie0302** [comment]
> The mixed tables situation is happening due to a simple reason. When docker compose spins up the containers, it has to assign a name to them: normally, when using `docker run`, if not explicitly provided the container name is randomly generated. Compose, on the other hand, uses as default container name (if no options are specified) the following structure: `${basename_dir}-${services}-${progr}`. So, if you start your compose file as-is, the database container will be named `backend-db-1`. See [this documentation](https://docs.docker.com/compose/environment-variables/envvars/#compose_project_name) for reference.
> 
> The problem, in this situation, is that the basename of the directory is "backend" for both the first and second MVP, so even though the docker-compose file is not the same (is in different location), by default it's not able to use anything to distinguish the different "projects", so to speak. Hence you end up reusing the same container that was created for the first MVP.
> 
> To solve this problem, you need to either (just the simplest options):
> 
> 1. Rename the backend folder (I do not recommend this).
> 2. Explicit a name for the Postgres container, which will be different from the one in the first MVP's docker compose file (as you did in this commit).
> 3. Specify a `name` variable in the compose config file (the cleanest one, in my opinion).
> 
> Note that there's no need to name the db, user and password differently, since the conflict is just due to using the same container. If you configure compose properly, another container will be created and you can keep the same credentials and names.
> 
> As a final note on Flyway: Flyway (as you might now guess from my explanation) has nothing to do with this issue and would not have solved this. It's a perfectly fine approach for progressively migrating and evolving the database schema alongside with the application code, but for this MVP is a bit overkill. We do not plan on evolving the application, so no incremental migration will have to be apply. You can certainly try and experiment with it if you have time when all the features are complete, but it's not mandatory to use it.
> 
> Hope I was clear, let me know if further explanation is needed.

Did not know about this possibility, but this is much smoother! Thank you for the comprehensive comment, never been in this situation before. If I misunderstood anything, let me know.

**Review by norrthons — APPROVED** [review]
Looks good

**Comment by norrthons** [comment]
This solution is easy and is working in Simons environment. It is, however, not working on mine. My docker compose version is too old and I do not think I will be able to update it to the necessary version (v2.3.3). 

Do you have any suggestions on how we could solve this issue?

**Comment by riccardobellini** [comment]
> This solution is easy and is working in Simons environment. It is, however, not working on mine. My docker compose version is too old and I do not think I will be able to update it to the necessary version (v2.3.3).
> 
> Do you have any suggestions on how we could solve this issue?

Do you have issues starting docker compose after the change which introduced the `name` variable, while before that change everything worked?

What's the error you are getting? Because I think the version of the compose file never changed, it's always been `3.1`.

@Simonlie0302 You could have just introduced the `name` variable, there's no need to change all the other configurations for postgres (db, user and new volume). The `name` only is enough to have Compose create a new container for the second mvp instead of reusing the one for the first, that's our goal.

**Comment by norrthons** [comment]
Yes. As soon as I try to run docker-compose up, I get the following message:

_ERROR: The Compose file './docker-compose.yml' is invalid because:
Invalid top-level property "name". Valid top-level sections for this Compose file are: version, services, networks, volumes, secrets, configs, and extensions starting with "x-".

You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/_

I have tries to change the version in the file, with no luck. What I did find was that the name variable was introduced in the docker compose version v2.3.3. When I look in my docker desktop, my compose is version 1.27.4. 

Before Simon added these changes, I could run it with no problem (but there was probably problems with being connected to the old project).

Now it I only remove the name variable, the docker-compose starts, but the ./mvnw spring-boot:run won't finish (at least not in a reasonable time). If I instead go back to the old docker compose, they both start and I can get the webpage to work.

I also tries to take away the other changes that Simon added but to keep the name variable, but with no luck. I got the same error then.

I hope this made my issue clearer.

**Comment by riccardobellini** [comment]
Ok, then it's indeed a problem with your version of Compose.

At this point, you have to manually remove the container created by the previous mvp, issue `docker ps -a` in a terminal to find its name, but it should be `backend-db-1`. Once you have found the name, run `docker rm $name`.
Then remove the offending line from the Compose file and retry `docker-compose up`, it should create another container with the same name, but the db will be empty because the old container was dropped.

Obviously, after you do this you shall not commit the Compose file with the changes that make it work on your local environment.

**Comment by norrthons** [comment]
Okay, I can do that. 

I have a question though. When I look at my databases, I do have one called `backend-db-1`, it says it was created 26 minutes ago though (see attached screen shot). Is that just because it tells me a new one is created every time I use it, but it actually just uses the same?

Skärmavbild 2024-05-10 kl  16 47 17

**Comment by riccardobellini** [comment]
I really have no idea, I think you should be right and that should be the
date it was first created, but I don't know. Only thing you can do is to
stop the compose, try to remove it and restart the compose to see if it
creates an empty db.

Let me know!


Il ven 10 mag 2024, 16:50 norrthons ***@***.***> ha scritto:

**Comment by Simonlie0302** [comment]
> > This solution is easy and is working in Simons environment. It is, however, not working on mine. My docker compose version is too old and I do not think I will be able to update it to the necessary version (v2.3.3).
> > Do you have any suggestions on how we could solve this issue?
> 
> Do you have issues starting docker compose after the change which introduced the `name` variable, while before that change everything worked?
> 
> What's the error you are getting? Because I think the version of the compose file never changed, it's always been `3.1`.
> 
> @Simonlie0302 You could have just introduced the `name` variable, there's no need to change all the other configurations for postgres (db, user and new volume). The `name` only is enough to have Compose create a new container for the second mvp instead of reusing the one for the first, that's our goal.

Yes, I know, but I thought it wouldn't make a difference with the changes. In the new branch(be_questionsEndpont) there is a lot of changes regarding the structure of the controllers and multiple endpoints. I will make a PR, but not merge it before our meeting on Tuesday so we can discuss it in person

@norrthons Try to do docker-compose down before starting docker-compose up again, you can also remove volumes if necessary(docker-compose down --volumes).

**Pull request merged**
